# Generated by Django 6.0.4 on 2026-05-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('admin', 'Admin'), ('online', 'Online')], default='walk_in', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery')], max_length=50, null=True),
        ),
    ]
