# Generated by Django 6.0.4 on 2026-05-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmep', '0002_sale_type_alter_sale_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='type',
        ),
    ]
